// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: updateuser.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const updateUserPasswordEmail = `-- name: UpdateUserPasswordEmail :exec
UPDATE users
SET email = $1,
    hashed_password = $2,
    updated_at = NOW()
WHERE id = $3
`

type UpdateUserPasswordEmailParams struct {
	Email          string
	HashedPassword string
	ID             uuid.UUID
}

func (q *Queries) UpdateUserPasswordEmail(ctx context.Context, arg UpdateUserPasswordEmailParams) error {
	_, err := q.db.ExecContext(ctx, updateUserPasswordEmail, arg.Email, arg.HashedPassword, arg.ID)
	return err
}
